org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

java_version=21

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# Fabric
fabric_loom_version=1.17.13
fabric_loader_version=0.19.3
fabric_api_version=0.116.13+1.21.1

# Forge
forgegradle_version=[7.0.3,8)
forge_version=52.1.14
forge_loader_version_range=[52,)

# NeoForge
moddevgradle_version=2.0.141
neoforge_version=21.1.235
neoforge_loader_version_range=[1,)
neoforge_minecraft_version_range=[1.21.1]

mod_group_id=net.craftmaster08
mod_authors=CraftMaster2008
mod_license=MIT
