modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="playtimeleaderboard"
namespace="playtimeleaderboard"
version="0.3-1.20.1"
displayName="Playtime-Leaderboard"
description="Shows a formatted leaderboard of playtime statistics."
authors="CraftMaster2008"

[[dependencies.playtimeleaderboard]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"
[[dependencies.playtimeleaderboard]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="SERVER"
[[dependencies.playtimeleaderboard]]
modId="cm08statscore"
mandatory=true
versionRange="[0.2,1.0)"
ordering="AFTER"
side="SERVER"