package net.craftmaster08.cm08statscore.config;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import net.minecraft.ChatFormatting;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class ConfigLoader {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final Logger LOGGER = LogManager.getLogger(ConfigLoader.class);

    static void load(File configFile, ConfigManager manager) {
        try (FileReader reader = new FileReader(configFile)) {
            JsonObject configJson = GSON.fromJson(reader, JsonObject.class);
            if (configJson == null) {
                throw new JsonParseException("Config file is empty or invalid JSON");
            }

            Map<String, ChatFormatting> tempUsernameColors = new HashMap<>();
            if (configJson.has("username_colors")) {
                JsonObject usernameColorsJson = configJson.getAsJsonObject("username_colors");
                for (Map.Entry<String, com.google.gson.JsonElement> entry : usernameColorsJson.entrySet()) {
                    String username = entry.getKey();
                    String colorName = entry.getValue().getAsString().toUpperCase();
                    ChatFormatting color = ChatFormatting.getByName(colorName);
                    if (color == null || !color.isColor()) {
                        LOGGER.warn("Invalid Minecraft color for {}: {}", username, colorName);
                        continue;
                    }
                    tempUsernameColors.put(username, color);
                }
            }

            Set<String> tempBlacklistedPlayers = new HashSet<>();
            if (configJson.has("blacklisted_players")) {
                configJson.getAsJsonArray("blacklisted_players")
                        .forEach(element -> {
                            String player = element.getAsString();
                            tempBlacklistedPlayers.add(player);
                            LOGGER.info("Loaded blacklisted player: {}", player);
                        });
            }

            Map<String, Integer> tempIntLimits = new HashMap<>();
            if (configJson.has("intlimits")) {
                JsonObject intLimitsJson = configJson.getAsJsonObject("intlimits");
                for (Map.Entry<String, com.google.gson.JsonElement> entry : intLimitsJson.entrySet()) {
                    String username = entry.getKey();
                    int limitCount = entry.getValue().getAsInt();
                    if (limitCount >= 0) {
                        tempIntLimits.put(username, limitCount);
                        LOGGER.info("Loaded intlimit for {}: {}", username, limitCount);
                    } else {
                        LOGGER.warn("Invalid intlimit count for {}: {}", username, limitCount);
                    }
                }
            }

            String tempDailyResetTime = configJson.has("daily_reset_time")
                    ? configJson.get("daily_reset_time").getAsString()
                    : "00:00:00 UTC";

            int tempCooldownSeconds = configJson.has("cooldown_seconds")
                    ? configJson.get("cooldown_seconds").getAsInt()
                    : 5;

            manager.usernameColors = Map.copyOf(tempUsernameColors);
            manager.blacklistedPlayers = Set.copyOf(tempBlacklistedPlayers);
            manager.intLimits = Map.copyOf(tempIntLimits);
            manager.dailyResetTime = tempDailyResetTime;
            manager.cooldownSeconds = tempCooldownSeconds;

            if (!configJson.has("cooldown_seconds")) {
                LOGGER.info("Added missing 'cooldown_seconds' to existing config");
                save(manager);
            }

            LOGGER.info("Successfully loaded statscore_config.json");
        } catch (IOException | JsonParseException e) {
            LOGGER.error("Failed to load statscore_config.json", e);
            resetToDefaults(manager);
        }
    }

    static void save(ConfigManager config) {
        JsonObject configJson = new JsonObject();
        configJson.addProperty("_comment", "DO NOT EDIT THIS FILE MANUALLY. Use /statsconfig commands to modify settings.");
        configJson.addProperty("daily_reset_time", config.dailyResetTime);

        JsonObject usernameColorsJson = new JsonObject();
        config.getUsernameColors().forEach((username, color) ->
                usernameColorsJson.addProperty(username, color.getName().toUpperCase()));
        configJson.add("username_colors", usernameColorsJson);

        com.google.gson.JsonArray blacklistedPlayersJson = new com.google.gson.JsonArray();
        config.getBlacklistedPlayers().forEach(blacklistedPlayersJson::add);
        configJson.add("blacklisted_players", blacklistedPlayersJson);

        JsonObject intLimitsJson = new JsonObject();
        config.getIntLimits().forEach(intLimitsJson::addProperty);
        configJson.add("intlimits", intLimitsJson);

        configJson.addProperty("cooldown_seconds", config.cooldownSeconds);

        try (java.io.FileWriter writer = new java.io.FileWriter(ConfigManager.CONFIG_PATH.toFile())) {
            new com.google.gson.GsonBuilder().setPrettyPrinting().create().toJson(configJson, writer);
            LOGGER.info("Saved statscore_config.json");
        } catch (java.io.IOException e) {
            LOGGER.error("Failed to save statscore_config.json", e);
            throw new RuntimeException("Failed to save configuration", e);
        }
    }

    static void createDefaultConfig(File configFile) {
        JsonObject defaultConfig = new JsonObject();
        defaultConfig.addProperty("_comment", "DO NOT EDIT THIS FILE MANUALLY. Use /statsconfig commands to modify settings.");
        defaultConfig.addProperty("daily_reset_time", "00:00:00 UTC");
        defaultConfig.add("username_colors", new JsonObject());
        defaultConfig.add("blacklisted_players", new com.google.gson.JsonArray());
        defaultConfig.add("intlimits", new JsonObject());
        defaultConfig.addProperty("cooldown_seconds", 5);

        try (FileWriter writer = new FileWriter(configFile)) {
            GSON.toJson(defaultConfig, writer);
            LOGGER.info("Created default statscore_config.json at {}", configFile.getAbsolutePath());
        } catch (IOException e) {
            LOGGER.error("Failed to create default statscore_config.json", e);
        }
    }

    private static void resetToDefaults(ConfigManager manager) {
        LOGGER.warn("Resetting to default configuration");
        manager.usernameColors = Map.of();
        manager.blacklistedPlayers = Set.of();
        manager.intLimits = Map.of();
        manager.dailyResetTime = "00:00:00 UTC";
        manager.cooldownSeconds = 5;
    }
}
