org.gradle.jvmargs=-Xmx4G
minecraft_version=1.20.1
forge_version=47.4.0
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=cm08statscore
mod_name=StatsCore
mod_version=0.2-1.20.1
mod_group_id=net.craftmaster08.cm08statscore
mod_authors=CraftMaster2008
mod_description=Library Mod for all statistics mods by CraftMaster2008.
mod_license=MIT
minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)
loader_version_range=[47,)